[package]
name = "ascua-macro"
description = "Compilador de templates de Ascua: la macro view! { } y su codegen a operaciones de DOM."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
ascua-css = { path = "../ascua-css" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[lints]
workspace = true
